remote: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: true
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: true
  week: true
  24 hours: true

positions:
  - Data Engineer
  - Data Scientist
  - Machine Learning Engineer
  - ETL Developer
  - ML Ops Engineer
  - Python Developer

locations:
  - Irvine, California, United States
  - San Diego, California, United States
  - California
  - United States
  - Canada

apply_once_at_company: True

distance: 50

company_blacklist:
  - Rithmm
  - SigFig

title_blacklist:

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 200

llm_model_type: openai
llm_model: 'gpt-4o-mini'
llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'